# Generated by Django 4.1.7 on 2023-02-28 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
    ]
